import { Geist, Geist_Mono, Manrope, Noto_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-body-manrope",
  subsets: ["latin"],
});
const noto_serif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${noto_serif.variable} h-full antialiased`}
    >
     <head>
       <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
     </head>
     <body>
        <div className="wholeWrapper">
      <Header />
        {children}
         
              <Footer />
    </div>
        </body>
    </html>
  );
}
